### ISSUE TITLE
Reg user can logout

### ISSUE THREAD

**Issue by scmountain** [CjMoore/cloney_island#11]
as a registered user, 
when you click logout
you are taken to the login
you can see login in nav bar

**Comment by s-espinosa** [comment]
@scmountain Currently this doesn't take me to the home page, but instead to login. Recommend either changing to match the user story or provide a reason to keep the existing functionality.

**Comment by scmountain** [comment]
@s-espinosa, there is often confusion when logging out, "did it really log me out?" so instead of leaving any questions in the mind of a beautiful user. I figured I would let them be as worry free as possible, seeing that "login" page would really allow them that peace of mind ;)
