### ISSUE TITLE
User new login

### ISSUE THREAD

**Issue by CjMoore** [CjMoore/cloney_island#2]
As a Guest 
	When I click login 
	I am at the route ‘/login’ 
	I see a form to submit username and password
	And a button to login with facebook
	I also see a button to create an account.

**Comment by CjMoore** [comment]
- "sessions#new"

**Comment by CjMoore** [comment]
- create sessions controller
- users migration and model creation

**Comment by scmountain** [comment]
DONE, but no FB

**Comment by s-espinosa** [comment]
:+1:
