### ISSUE TITLE
Display owned projects on user profile

### ISSUE THREAD

**Issue by CjMoore** [CjMoore/cloney_island#25]
As a project owner
	When they visit ‘/username’
	They see their user information(as detailed in registered user)
	They see a table with all of their owned projects
		The table includes project name
			Each project name is a link to the project show
		Total amount 
		Total Funded 
		Remaining Time
		There is a button labeled “Edit”
		There is a button labeled “Disable"

**Comment by CjMoore** [comment]
- use user.owned_project relationship to display owned projects on user profile
- buttons are placeholders

**Comment by scmountain** [comment]
thanks G

**Comment by edilenedacruz** [comment]
:)
