### ISSUE TITLE
Add table of funded projects to user profile

### ISSUE THREAD

**Issue by CjMoore** [CjMoore/cloney_island#45]
as a project funder
when I visit ‘/:username’ 
I can see a table with all the projects I have funded
	There is a column for the name
		Each name is a link to project show
	There is a column for time remaining
	There is a column for total amount funded
	There is a column for total needed
	There is a column for total I have funded

**Comment by s-espinosa** [comment]
@cews7 Looks like there's currently a vulnerability here where I can see other user's information by just entering their username into the address bar.

**Comment by cews7** [comment]
@s-espinosa Spencer fixed this.
