### ISSUE TITLE
Add registered user permissions

### ISSUE THREAD

**Issue by CjMoore** [CjMoore/cloney_island#50]
- add registered user role to logged in user

**Comment by s-espinosa** [comment]
@edilenedacruz @scmountain Not sure this needs to be in `Implemented`. Seems like it's a smaller story that will lead to a larger user story that I could review for functionality.

**Comment by scmountain** [comment]
@s-espinosa, this was more of a syntax change. logged user is now called registered user. more official and would help our client in the future when this code is in the hands of diff devs...
