### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by CjMoore** [CjMoore/cloney_island#7]
As a Guest
	When I am on the login page 
	And I click Create Account
	I am taken to “/users/new”
	I see a form 
	There is a field for username, email, password, password confirmation

**Comment by CjMoore** [comment]
- "user#new"

**Comment by CjMoore** [comment]
- create users controller

**Comment by s-espinosa** [comment]
Believe we discussed changing this story to have the route be `/signup`. Can you confirm?

**Comment by CjMoore** [comment]
it is /signup
